# Default (rake cucumber / cucumber).
default: --format pretty --strict --drb features

# Wip (rake cucumber:wip / cucumber --profile wip).
# Run only @wip tags, maximum of 3 allowed.
wip: --format pretty --drb --tags @wip:3 --wip features

# Rerun: (see here: http://devnet.jetbrains.net/message/5261019)
<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
%>
rerun: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip